version: '2'

networks:
  efk_hostnet:
    external: true

services:
  frontend:
    build: .
    image: frontend
    container_name: front
    networks:
      - efk_hostnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/utah/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/icoworld.network/fullchain.pem:/etc/letsencrypt/live/icoworld.network/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/icoworld.network/privkey.pem:/etc/letsencrypt/live/icoworld.network/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    external_links:
      - backend
