version: '2'

networks:
  hostnet:
    external: true

services:
  
  frontend:
    build: .
    env_file: 
      - "/var/icoworld/front.env"
    image: frontend
    container_name: front
    networks:
      hostnet:
        ipv4_address: 172.18.0.130
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.18.0.10:24224
        tag: frontend.log
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/utah/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/icoworld.network/fullchain.pem:/etc/letsencrypt/live/icoworld.network/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/icoworld.network/privkey.pem:/etc/letsencrypt/live/icoworld.network/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    external_links:
      - backend
