version: '2'

networks:
  efk_fluentd:
    external: true

services:
  frontend:
    build:
      context: .
      args:
        API_ENDPOINT: "//icoworld.projects.oktend.com:80"
    image: frontend
    container_name: front
    networks:
      - efk_fluentd
    ports:
      - "80:80"
    external_links:
      - backend
